#!/bin/bash

if [ -d "$1" ]; then
	db_name=$(basename $(cd $1 2> /dev/null && pwd -P))

	echo "db named wp_test_$db_name removing..."
    mysql -u root -e "DROP DATABASE wp_test_$db_name;"

	folder_name=$(cd $1 2> /dev/null && pwd -P)

	echo "folder $folder_name removing..."
	rm -rf $(cd $1 2> /dev/null && pwd -P)

    # Close all php server instances
	echo "killing php servers..."
    ps aux | grep php | awk '{print $2}' | xargs kill -9 &>/dev/null

	echo "done"
fi

