#!/bin/bash

cd $(git rev-parse --show-toplevel)

if [ -z "$1" ]
then
	ln -s $(pwd) "$(wp-path)/wp-content/plugins"
else
	if [ -d ~/Projects/full/wp_installs/$1 ]
	then
		ln -s $(pwd) ~/Projects/full/wp_installs/$1/wp-content/plugins
	fi
fi

